### ISSUE TITLE
您好,我是新手,请问编译之后chrome运行白屏什么问题?

### ISSUE THREAD

**Issue by melontaro** [PhotoArtLife/uniapp-scaffold#5]
运行到hb内置浏览器也是白屏,报错内容如下:
11:00:14.437  INFO  Starting development server...
11:00:28.827 App Hide  at App.vue:61
11:00:29.092   App running at:
11:00:29.097   - Local:   http://localhost:8080/ 
11:00:29.098   - Network: http://192.168.1.103:8080/
11:00:29.104 项目 'uniapp-scaffold' 编译成功。前端运行日志，请另行在浏览器的控制台查看。
11:00:29.104 H5版常见问题参考: https://ask.dcloud.net.cn/article/35232
11:00:29.146 App Show  at App.vue:58
11:00:29.434 App Hide  at App.vue:61
11:00:29.733 App Show  at App.vue:58
11:00:29.836 [system] [object] {"message":"Cannot read property 'height' of undefined","stack":"TypeError: Cannot read property 'height' ...} 
11:00:29.836 [system] [object] {"message":"Cannot read property 'height' of undefined","stack":"TypeError: Cannot read property 'height' ...} 

--------------------------------------------------
hb最新版安装的插件有:

1. es6编译
2. eslint-plugin-vue
3. less编译
4. prettier
5. scss/sass编译
6. stylelint
7. stylus-supermacy
8. typescript编译
9. uniapp编译
10. 内置浏览器
11. 内置终端

期待您的回复!

**Comment by mukuashi** [comment]
1. 建议用HbuildX最新版IDE；
2. 可以通过微信开发者工具切换pages.json中condition配置的页面，或者关闭微信开发者工具，然后再从HBuilderX中启动指定页
3. 如果出现微信开发者工具启动后白屏的问题，检查是否启动多个微信开发者工具，如果是则关闭所有打开的微信开发者工具，然后再重新运行

**Comment by melontaro** [comment]
> 1. 建议用HbuildX最新版IDE；
> 2. 可以通过微信开发者工具切换pages.json中condition配置的页面，或者关闭微信开发者工具，然后再从HBuilderX中启动指定页
> 3. 如果出现微信开发者工具启动后白屏的问题，检查是否启动多个微信开发者工具，如果是则关闭所有打开的微信开发者工具，然后再重新运行
